package de.kraemer.tim.tippspiel.room;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/room") // This means URL's start with /demo (after Application path)
public class RoomController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private RoomRepository roomRepository;
	
	@GetMapping(path="/list")
	public String Rooms(Model model) {
		model.addAttribute("rooms", roomRepository.findAll());
		return "rooms";
	}
}