package de.kraemer.tim.tippspiel.controller;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;

import de.kraemer.tim.tippspiel.Entities.Account;
import de.kraemer.tim.tippspiel.forms.AccountData;
import de.kraemer.tim.tippspiel.repositories.AccountRepository;

@Controller
@RequestMapping(path="/")
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private AccountRepository accountRepository;

	@GetMapping("/")
    public String home() {
        return "home";
    }

	@GetMapping("/login")
    public String login(Model model) {
        model.addAttribute("accountData", new AccountData());
        return "Login";
    }

    @PostMapping("/login")
    public String loginResponse(AccountData accountData, HttpSession session, Model model) {
    	Account account = accountRepository.findFirstByName(accountData.getName());
    	if ((account != null) && account.getPassword().equals(accountData.getPassword()))
    	{
    		session.setAttribute("account", account);
    		session.setAttribute("isLoggedIn", true);
    		return "redirect:/";
    	}
    	
    	model.addAttribute("error", "loginData not correct");
        return "login";
    }
    
    @GetMapping("/logout")
    public String logout(HttpSession session) {
		session.removeAttribute("account");
		session.removeAttribute("isLoggedIn");
		return "redirect:/";
    }
    
    @GetMapping("/register")
    public String register(Model model) {
        model.addAttribute("accountData", new AccountData());
        return "register";
    }

    @PostMapping("/register")
    public String registerResponse(AccountData accountData, HttpSession session, Model model) {
    	Account account = accountRepository.findFirstByName(accountData.getName());
    	if (account == null)
    	{
    		account = new Account();
    		account.setName(accountData.getName());
    		account.setPassword(accountData.getPassword());
    		accountRepository.save(account);
    		
    		session.setAttribute("id", account.getId());
    		session.setAttribute("isLoggedIn", true);
    		return "redirect:/";
    	}
    	
    	model.addAttribute("error", "Benutzer existiert bereits");
        return "register";
    }
}