package de.kraemer.tim.tippspiel.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import de.kraemer.tim.tippspiel.Entities.Room;
import de.kraemer.tim.tippspiel.Entities.Theme;
import de.kraemer.tim.tippspiel.forms.RoomData;
import de.kraemer.tim.tippspiel.forms.ThemeData;
import de.kraemer.tim.tippspiel.repositories.RoomRepository;
import de.kraemer.tim.tippspiel.repositories.ThemeRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/theme") // This means URL's start with /demo (after Application path)
public class ThemeController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private ThemeRepository themeRepository;
	@Autowired
	private RoomRepository roomRepository;
	
	@GetMapping(path="/list")
	public String Rooms(Model model) {
        model.addAttribute("themeData", new ThemeData());
        model.addAttribute("roomData", new RoomData());
		model.addAttribute("themes", themeRepository.findAll());
		return "themes";
	}
	
	@PostMapping(path="/add")
	public String addNewTheme (ThemeData themeData) {
		Theme theme = new Theme();
		theme.setDescription(themeData.getDescription());
		theme.setTitle(themeData.getTitle());
		themeRepository.save(theme);
		return "redirect:/theme/list";
	}
	
	@GetMapping(path="/{id}/show")
	public String ShowRoomByID(@PathVariable int id, Model model) {
		model.addAttribute("theme",themeRepository.findOne(id));
		return Rooms(model);
	}
	
	@PostMapping(path="/{id}/createRoom")
	public String GetThemeByID(@PathVariable int id, Model model, RoomData roomData) {
		Theme theme = themeRepository.findOne(id);
		
		Room room = new Room();
		room.setTheme(theme);
		room.setName(roomData.getName());
		theme.getRooms().add(room);
		roomRepository.save(room);
		
		model.addAttribute("theme", theme);
		return Rooms(model);
	}
}