package de.kraemer.tim.tippspiel.cardtype;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/cardtype") // This means URL's start with /demo (after Application path)
public class CardTypeController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private CardTypeRepository cardTypeRepository;
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<CardType> CardTypes() {
		// This returns a JSON or XML with the users
		return cardTypeRepository.findAll();
	}
}