package de.kraemer.tim.tippspiel.player;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;

import de.kraemer.tim.tippspiel.ControllerExtender;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/player") // This means URL's start with /demo (after Application path)
public class PlayerController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PlayerRepository playerRepository;
	
	@ModelAttribute
    public void addAttributes(Model model) {
        ControllerExtender.InsertHeaderModelAttributes(model);
    }
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Player> Players() {
		// This returns a JSON or XML with the users
		return playerRepository.findAll();
	}
}